Cartography/Constraint.swift

Resolve a compiler error: "Use of undeclared type 'NSLayoutConstraint'"

Update Constraint.swift to import UIKit or AppKit

---

Cartography.xcodeproj/project.pbxproj
Cartography/Context.swift
Cartography/ViewUtils.swift
CartographyTests/ViewHierarchyTests.swift

Fix ancestor algorithm

---

Cartography/ViewUtils.swift

Fix an issue that `NSSet` not being recognized.

Import Foundation if not testing

---

Cartography/Dimension.swift
Cartography/Edge.swift
Cartography/Property.swift

Make Edge not accept numbers for ==

---

Cartography/Extensions.swift

Fix CGFloat not being found

---

.travis.yml

Use xcpretty

---

Cartography/Layout.swift

Remove constraints of constraint group

---

Cartography/Context.swift
Cartography/ViewUtils.swift
CartographyTests/ViewHierarchyTests.swift

Throw an assert if no common superview is found

---

Cartography/Align.swift
Cartography/Context.swift
Cartography/Distribute.swift
Cartography/Edges.swift
Cartography/Point.swift
Cartography/Property.swift
Cartography/Size.swift
Cartography/View.swift
Cartography/ViewUtils.swift
CartographyTests/AlignTests.swift
CartographyTests/DistributeTests.swift

Only allow properties/compounds as lhs of (in)equality operators

---

Cartography/Context.swift

A single item should use append.  += is about 4 times slower

Micro-optimization.  += is slower for array append

---

Cartography/Constraint.swift
Cartography/ConstraintGroup.swift

Fixing the retain cycle on Constraint
Partially fixed issue #104

Avoiding a retain cycle on Constraint

---

Cartography.xcodeproj/project.pbxproj
Cartography/Context.swift
CartographyTests/MemoryLeakTests.swift

Fix memory leak

---

Cartography/ConstraintGroup.swift
Cartography/View.swift

Should've been removed in #63 :sweat:

Remove unnecessary code

---

.travis.yml
Cartfile.private
Cartfile.resolved

Restore .travis.yml

---

Cartography/LayoutProxy.swift

so this will compile in apps targeting iOS7

add @available annotations to iOS8-specific entries in LayoutProxy

---

Cartography.podspec
Cartography/Align.swift
Cartography/Compound.swift
Cartography/Constraint.swift
Cartography/Context.swift
Cartography/Dimension.swift
Cartography/Distribute.swift
Cartography/Edge.swift
Cartography/Edges.swift
Cartography/Extensions.swift
Cartography/LayoutProxy.swift
Cartography/Point.swift
Cartography/Priority.swift
Cartography/Property.swift
Cartography/Size.swift
Cartography/View.swift
Cartography/ViewUtils.swift

Since tvOS uses UIKit, this compiles just fine for tvOS. I tested it a little bit, but not very thoroughly and it seems to work alright.

Add support for tvOS

---

Cartography.xcodeproj/project.pbxproj

Added bitcode support as defined in: https://github.com/Carthage/Carthage/issues/535

Added bitcode support (see description)

---

Cartography.podspec

Update Podspec for release

---

README.md

Clarify versioning section

---

Cartography.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Cartography.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

When I opened projects with Xcode 9.3,
these files are generated.

commit Xcode9.3 meta files

---

.travis.yml
Cartography.xcodeproj/project.pbxproj
Cartography.xcodeproj/xcshareddata/xcschemes/Cartography-Mac.xcscheme
Cartography.xcodeproj/xcshareddata/xcschemes/Cartography-iOS.xcscheme
Cartography.xcodeproj/xcshareddata/xcschemes/Cartography-tvOS.xcscheme
Cartography/Context.swift
Cartography/LayoutProxy.swift
Cartography/Property.swift
CartographyTests/Matchers.swift
CartographyTests/TestView.swift
Podfile.lock

Convert to Swift 4.2.
