robb/Cartography

Cartography.xcodeproj/project.pbxproj, Cartography/Coefficients.swift, Cartography/Edges.swift, Cartography/Extensions.swift, Cartography/Property.swift, Cartography/Size.swift, CartographyTests/TypesTests.swift
By adding the `Number` protocol, we can handle `Float`, `Double` and `CGFloat` by simply promoting all of them to `Double`s without defining every operator thrice.
Fixes #56
=> Support CGFloat

Cartography/Coefficients.swift, Cartography/Edges.swift, Cartography/Extensions.swift, Cartography/Point.swift, Cartography/Priority.swift, Cartography/Property.swift, Cartography/Size.swift, Cartography/ViewUtils.swift
I'm really impressed by this repository. Thank you.
When I read code of this repository, I noticed one thing...
Code like below is a little bit not readable
the operator is <=? or <=< ? 
```
public func <=<P: RelativeInequality>(lhs: P, rhs: P) -> NSLayoutConstraint {
```
So I added a whitespace after the operator.
If you would like, please merge this...
Sorry for sending such a simple and ridiculous change.
Thank you.
=> Add whitespaces between custom operator and generics

Cartography.xcodeproj/project.pbxproj, Cartography/Align.swift, CartographyTests/AlignTests.swift, README.md
This adds multiple `align` methods that take a list of at least two `LayoutProxy` instances and align them by a given edge.
E.g.:
```swift
constrain(logIn, logOut, selfDestruct) {
// Equivalent to
//
//     logIn.bottom  == logOut.bottom
//     logOut.bottom == selfDesctruct.bottom
//
align(bottom: logIn, logOut, selfDesctruct)
}
```
/cc @mergesort
Fixes #77
=> Add align methods to align multiple views

Cartography.xcodeproj/project.pbxproj, Cartography/Distribute.swift, CartographyTests/DistributeTests.swift
Adds `distribute` methods to space out multiple views horizontally, vertically or left-to-right.
E.g.
```swift
constrain(logIn, logOut, selfDestruct) {
// Equivalent to
//
//     logIn.trailing  + 10 == logOut.leading
//     logOut.trailing + 10 == selfDesctruct.leading
//
distribute(by: 10, horizontally: logIn, logOut, selfDesctruct)
}
```
Fixes #85
=> Add distribute

Cartography/Context.swift
This fixes a defect where inequality operators would not call `setTranslatesAutoresizingMaskIntoConstraints` on the right hand side of an equality or inequality operator.
E.g.
```
view1.top == view2.top
view1.top == view3.top
```
was not equivalent to 
```
view1.top == view2.top
view2.top == view3.top
```
since the latter would call `setTranslatesAutoresizingMaskIntoConstraints(false)` on both `view1` and `view2`.
This change set disables the translation of autoresizing masks on the left-hand and right-hand operand of all equality and inequality operators.
=> Disable autoresizing mask constraints for rhs

Cartography/Context.swift, Cartography/View.swift
This stops Cartography from calling `setTranslatesAutoresizingMaskIntoConstraints(false)` on `UIView`s that are owned by `UIViewController`, since they may depend on their autoresizing mask-based constraints.
Fixes #87
=> Ignore UIViews owned by UIViewController

Cartography/Compound.swift, Cartography/Dimension.swift, Cartography/Edge.swift, Cartography/Edges.swift, Cartography/LayoutProxy.swift, Cartography/Point.swift, Cartography/Size.swift
This replaces all enums with vastly simpler structs and also moves the operators for `Compound` properties into protocols.
Depends on  #93
=> Refactor properties

Cartography/Distribute.swift
To reproduce:
1. Clone Cartography (Xcode 6.3 branch)
2. Create an empty Cocoa Xcode project
3. Drag Cartography classes in to the new project (like some sort of animal, I know)
4. See error, above.
(Only noted above as same class works in original project. Haven’t looked into why/how.)
=> Fixed “Use of undeclared type ‘NSLayoutConstraint’ error.

Cartography.podspec
This branch is not intended to be merged until Swift 1.2 leaves beta
Fixes #9
=> [BETA] Swift 1.2 compatiblity

Cartography/Constraint.swift
This is to fix the following compiler error:
```error: only classes that inherit from NSObject can be declared @objc```
=> Remove @objc declaration of the class Constraint

Cartography.xcodeproj/project.pbxproj
When I have Cartography in my Cartfile and run `carthage bootstrap` from a clean state (`rm -r Carthage`), I see some warnings:
```
*** Checking out Cartography at "0.6.0"
*** xcodebuild output can be found in /var/folders/m3/0g6_fk1n1pqb2kfq256zdwrw0000gp/T/carthage-xcodebuild.huS7L2.log
*** Building scheme "Cartography-iOS" in Cartography.xcodeproj
ld: warning: directory not found for option '-F/Users/asana/Documents/ios/Carthage/Checkouts/Cartography/Carthage/Build/iOS'
ld: warning: directory not found for option '-F/Users/asana/Documents/ios/Carthage/Checkouts/Cartography/Carthage/Build/iOS'
ld: warning: directory not found for option '-F/Users/asana/Documents/ios/Carthage/Checkouts/Cartography/Carthage/Build/iOS'
ld: warning: directory not found for option …
```
=> Warnings when building with Carthage

Cartography/LayoutProxy.swift
`LayoutProxy` didn't have a property for `NSLayoutAttribute.LastBaseline` so I added it myself. Or is there a reason for why it's missing?
I tested the code in my application and it looks like it's working.
=> Added the lastBaseline property to LayoutProxy

Cartography/Edges.swift, CartographyTests/EdgesSpec.swift
Adds a helper `inset` with takes a UIEdgeInsets parameter instead of specifying each edge separately.
Fixed version of https://github.com/robb/Cartography/pull/194
=> Allow insetting edges using UIEdgeInsets

Cartography.xcodeproj/project.pbxproj
It looks like y'all left off a few targets when running the migrator. No code changes were necessary, but Xcode wasn't aware that they supported Swift 2.3, so Carthage complained when trying to build for those platforms.
=> Mark all targets as supporting Swift 2.3

Cartography/Constrain.swift
while there is a optional constraintGroup that i have to replace it when it's not nil, i have do like this
var replaceGroup: ConstraintGroup?
if let replaceGroup = replaceGroup {
constrain(view, replace: replaceGroup) { view in
// new constrains
}
} else {
constrain(view) { view in
// new constrains
}
}
or
constrain(view, replace: replaceGroup ?? ConstraintGroup()) { view in
// new constrains
}
both are not convenient, so make the replaceGroup argument optional for convenient
=> Make the replaceGroup argument optional

Cartography.xcodeproj/project.pbxproj
I've also removed any references for this and `SWIFT_VERSION` in the targets, and only defined this at the project level:
=> Enabled whole module optimizations

Cartography/Priority.swift, CartographyTests/PrioritySpec.swift
This fixes the error “PrioritySpec.swift:22:28: Adjacent operators are in unordered precedence groups 'AssignmentPrecedence' and 'CarthographyPriorityPrecedence’” noted in issue https://github.com/robb/Cartography/issues/241
It also works around the bug “PrioritySpec.swift:22:48: Cannot assign value of type 'NSLayoutConstraint' to type 'NSLayoutConstraint!’” by switching out the priority Int for a Float.
This workaround is necessary as there’s a Swift compiler bug present.
References:
https://bugs.swift.org/browse/SR-2823
https://openradar.appspot.com/28582961
=> Priority fix and compiler bug workaround

Cartography/Constrain.swift
New Swift 3.1 is showing warning:
Constrain.swift:144:27: @discardableResult declared on a function returning Void is unnecessary
```
/// Removes all constraints for a group.
///
/// - parameter clear: The `ConstraintGroup` whose constraints should be removed.
///
@discardableResult public func constrain(clear group: ConstraintGroup) {
group.replaceConstraints([])
}
```
=> Swift 3.1 @discardableResult warning of constrain(clear group: ConstraintGroup)

README.md
I was about to contribute this change to support using `LayoutPriority` instead of raw values, but realized the latest version already supports this. I haven't been able to pinpoint when this changed though, all I could see is 9e2205c735aa2a4f00c8c8b0313501812cdd2414 updated some tests for it.
Edit: oh I just saw #271:
> In Swift 4, `UILayoutPriority` is a `RawRepresentable` instead of a `Float`
So that makes sense, this was a `Swift 4.0` change 👍
=> README.md: fixed ~ examples to use UILayoutPriority

Cartography/Priority.swift
In Swift 4, UILayoutPriority is a RawRepresentable instead of a Float, so passing numbers to the priority `~` operator no longer works out of the box.
This patch adds a function that takes a Float for the priority, and creates a UILayoutPriority from it. With this change, the Cartography DSL will stay compatible from Swift 3 to Swift 4.
Fixes the issue I opened here: #270
=> Add an overload to the priority operator ('~') that accepts a float.

README.md
I fixed README. It changed from `class func animateWithDuration(duration: TimeInterval, animations: @escaping () -> Void)`  to `class func animate(withDuration duration: TimeInterval, animations: @escaping () -> Void)` since Swift 3 later.
https://developer.apple.com/documentation/uikit/uiview/1622418-animate
=> Update README: fixed syntax for swift3 later

Cartography.xcodeproj/project.pbxproj, Cartography.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Cartography.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
tvOS target can not be compiled.
It is from just forgotten to add `LayoutItem.swift` to target.
I add this source to target and makes it can be compiled.
This PR include #288
=> Fix build error in tvOS

Cartography/LayoutProxy.swift
`NSLayoutConstraint` is part of `UIKit` / `AppKit` so they need to be imported here when using alternative build systems to Xcode.
=> Add missing UIKit and AppKit imports

Cartography.podspec
`swift_version` is supported as of [Cocoapods 1.4](https://blog.cocoapods.org/CocoaPods-1.4.0/#swift-version-dsl). Adding this removes the requirement that the pod be integrated into a target which uses the same Swift version.
=> Add Swift version to podspec

Cartography.xcodeproj/project.pbxproj, Cartography/ViewProxy.swift, CartographyTests/ViewLayoutGuideSpec.swift, CartographyTests/ViewProxyTests.swift, Podfile.lock
Since now we have a new safe area layout guide, it can get messy if we need to use it when compiling for iOS versions prior to 11.
This is a small helper to make it cleaner when you need to use `SafeAreaLayoutGuide`.
=> Simple helper for use SafeAreaLayoutGuide if available

Package.swift
This adds support for SwiftPM manifest based dependency managers. Specifically this adds support for installing via [Accio](https://github.com/JamitLabs/Accio) but will probably also work with SwiftPM once it's integrated into Xcode.
=> Add basic SwiftPM manifest file

Cartography/ViewProxy.swift
The added ViewProxy-helper `var safeArea` wasn't public, so it wasn't accessible.
=> Make ViewProxy.safeArea public

Cartography/Coefficients.swift
Every other `import UIKit` has this except for this file.
Because of this Cartography is failing to build on tvOS.
=> Added missing import for tvOS

Cartography.xcodeproj/project.pbxproj
Added flag to the `Mac` target so it can be built for Catalyst.
This is needed when building with the future version of `Carthage` supporting Catalyst.
=> SUPPORTS_MACCATALYST

Cartography.xcodeproj/project.pbxproj
See [Xcode 10's known issues](https://developer.apple.com/documentation/xcode-release-notes/build-system-release-notes-for-xcode-10) in the release notes:
> Targets with Copy Headers build phases ordered after Compile Sources build phases may fail to build and emit a diagnostic regarding build cycles. (39880168)
>*Workaround*: Arrange any Copy Headers build phases before Compile Sources build phases.
This has been an issue for nearly 4 years, and now with Xcode 13.3 it leads to `XCBBuildService` to crash consistently.
=> Fixed build phases order
